version: '3'
services:
  shop_api_back:
    build:
      context: .
    command: sh -c "sleep 10 && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8001:8000" # host:container
    depends_on:
      - shop_db
  shop_db:
    image: 'postgres:14'
    environment:
      POSTGRES_DB: data_shop
      POSTGRES_USER: data_shop_user
      POSTGRES_PASSWORD: 1234
    volumes:
      - 'shop-data:/var/lib/postgres/data'
volumes:
  shop-data: